networks:
  fallout-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  kafka_data:

# kafka-ui, prometheus, grafana, gateway, eureka, other services
services:

  redis:
    image: redis:8.8.1
    container_name: fallout-redis
    networks:
      - fallout-network
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  postgres:
    image: postgres:18.0-alpine
    container_name: fallout-postgres
    networks:
      - fallout-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    restart: unless-stopped


  kafka:
    image: apache/kafka:4.3.1
    container_name: fallout-kafka
    restart: unless-stopped
    networks:
      - fallout-network
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      start_period: 30s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-fallout
    restart: unless-stopped
    ports:
      - "8084:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - fallout-network
    depends_on:
      kafka:
        condition: service_healthy

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-fallout
    restart: unless-stopped
    ports:
      - "8085:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - fallout-network
    depends_on:
      redis:
        condition: service_healthy