spring:
  application:
    name: lobby
  datasource:
    url: jdbc:postgresql://localhost:5432/fallout_lobby
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Fallout-Hicari-Pool [Lobby-Service]
      minimum-idle: 10
      maximum-pool-size: 50
  liquibase:
    change-log: classpath:db/migrations/changelog-master.yaml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/${POSTGRES_DB:fallout}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USER:default}
      password: ${REDIS_PASSWORD:password}
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 30
          min-idle: 10
  services:
    broadcast:
      url: http://localhost:8090

